### ISSUE TITLE
Forbid outside API access

### ISSUE THREAD

**Issue by SkytAsul** [InsaLan/langate3000#18]
### Description

Forbid access to the API except for the docker that contains the gate backend.

### Indications
I can think of 2 possibilities
1. Via an nftables rule at launchtime?
2. By binding the API to the docker bridge IP so it is only accessible from containers.

**Comment by pixup1** [comment]
```python
self._execute_nft_cmd("add rule insalan saddr != {IP_DOCKER_BACKEND} tcp dport 6784 drop")
```

?

**Comment by SkytAsul** [comment]
La solution 2 est meilleure. Sinon oui ce genre de rule marcherait.
