### ISSUE TITLE
Integrate ip rules into netcontrol

### ISSUE THREAD

**Issue by pixup1** [InsaLan/langate3000#31]
### Description

Since we're integrating [portail.sh](https://github.com/InsaLan/scripts-reseau/blob/nftables/portail.sh) into netcontrol, we might as well integrate [ip_rules.sh](https://github.com/InsaLan/scripts-reseau/blob/nftables/ip_rules_insalan.sh) directly into netcontrol, in a dynamic way that depends on the amount of marks and vpns.

It could fetch the number of VPNS from `/etc/hosts`, for example (see [vpn_register.py](https://github.com/InsaLan/VPNator/blob/master/vpn_register.py)).

**Comment by SkytAsul** [comment]
I'd see the number of VPNs stored somewhere in variables.json so it can also be used in autoroute_aec.

**Comment by pixup1** [comment]
This feature is acually not needed, in fact it could be inconvenient. Whoops
