### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by KwikKill** [InsaLan/langate3000#9]
### Type of Issue

- [ ] Bug
- [ ] Feature Request
- [X] Documentation
- [ ] Other

### Description

One of the main reason for this langate rewrite is the need for documentation. We will have 2 docs, one technical documentation as a mdbook example in the [website backend](https://github.com/InsaLan/backend-insalan.fr/tree/dev/docs) and the user documentation in the insalan wiki.

CI also need to be auto-deploying doc.

**Comment by pixup1** [comment]
For the auto deployment, we can either copy [deploy_docs.sh](https://github.com/InsaLan/infra-insalan.fr/blob/main/docs/deploy_docs.sh) to this repo, or just update [mappings.txt](https://github.com/InsaLan/infra-insalan.fr/blob/main/docs/mappings.txt) in the infra-insalan repo
